name: '🐛 Bug report'
description: 'Report a bug to help us improve this project, regardless of language or tech stack.'
labels:
 - 'bug'
assignees:
 - 'k4itrun'
body:
 - type: textarea
   id: environment
   attributes:
    label: 'Environment'
    description: 'Describe the environment where the bug occurred (e.g., OS, programming language, framework, browser, device, etc.).'
    placeholder: |
     - OS: Windows 11, Ubuntu 24.04, macOS Sonoma, Android 14, etc.
     - Programming language: Python 3.12, Java 21, JavaScript (Node.js 20), etc.
     - Framework/Runtime: Django 5.0, React 18, .NET 8, etc.
     - Browser/App (if applicable): Chrome 123, Firefox 120, Safari 17, etc.
     - Device: Desktop, iPhone 15, Raspberry Pi, etc.
   validations:
    required: true

 - type: input
   id: version
   attributes:
    label: 'Project/Module/Package Version'
    description: 'What version of the software, package, or component are you using?'
    placeholder: 'e.g., v2.1.3, 1.0.0-beta, commit hash, etc.'
   validations:
    required: true

 - type: textarea
   id: steps-to-reproduce
   attributes:
    label: 'Steps to Reproduce'
    description: 'List the exact steps needed to trigger the bug. Include commands, configs, inputs, or data as needed for any language or environment.'
    placeholder: |
     1. Clone the repository
     2. Run `npm install` (or `pip install -r requirements.txt`, etc.)
     3. Start the app with `npm start` (or `python main.py`, etc.)
     4. Navigate to the settings page
     5. Click "Save" without changing anything
   validations:
    required: true

 - type: textarea
   id: expected-behavior
   attributes:
    label: 'Expected Behavior'
    description: 'Describe what you expected to happen if the bug was not present.'
    placeholder: 'e.g., The settings should save without errors.'
   validations:
    required: true

 - type: textarea
   id: actual-behavior
   attributes:
    label: 'Actual Behavior'
    description: 'Describe what actually happened. Be specific and include error messages, stack traces, or incorrect results.'
    placeholder: 'e.g., Received a 500 error and settings were not saved.'
   validations:
    required: true

 - type: textarea
   id: logs
   attributes:
    label: 'Relevant Logs or Output (optional)'
    description: 'Paste any error messages, stack traces, or console output related to the bug. (Redact sensitive info.)'
    placeholder: |
     ```
     Traceback (most recent call last):
       File "main.py", line 42, in <module>
         run_app()
     ...
     ```
   validations:
    required: false

 - type: textarea
   id: screenshots
   attributes:
    label: 'Screenshots or Recordings (optional)'
    description: 'Attach screenshots or videos to illustrate the issue, if possible.'
    placeholder: 'Drag and drop images or videos here.'
   validations:
    required: false

 - type: dropdown
   id: severity
   attributes:
    label: 'Bug Severity'
    description: 'How badly does this bug impact the project?'
    options:
     - 'Critical: blocks all or most functionality'
     - 'Major: affects key features'
     - 'Minor: some impact, workaround exists'
     - 'Trivial: cosmetic or very low impact'
   validations:
    required: true

 - type: dropdown
   id: priority
   attributes:
    label: 'Priority to Fix'
    description: 'How urgently should this be fixed?'
    options:
     - 'High'
     - 'Medium'
     - 'Low'
   validations:
    required: true

 - type: dropdown
   id: type
   attributes:
    label: 'Bug Category'
    description: 'Select one or more categories that best describe the bug.'
    multiple: true
    options:
     - 'Functional'
     - 'Performance'
     - 'User Interface'
     - 'Compatibility'
     - 'Security'
     - 'Documentation'
     - 'Other'
   validations:
    required: true

 - type: textarea
   id: additional-information
   attributes:
    label: 'Additional Information'
    description: |
     Share any extra context, configuration files, edge cases, related issues, or links that could help us investigate.
    placeholder: 'Paste configs, describe edge cases, or add any other helpful details here.'
   validations:
    required: false
